import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  /*
  aquaticCrates: [
    { type: 'ref', id: 'aquaticcrates/intro' },
    {
      type: 'link',
      label: '💲 Purchase Here',
      href: 'https://aquatic.gg/products/aquaticcrates',
    },
    /*
    {
      type: 'category',
      label: 'Basics',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'aquaticcrates/basic' },
      ],
    },
    {
      type: 'category',
      label: 'Miscellaneous',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'ref', id: 'global/blocksettings' },
        { type: 'ref', id: 'global/itemsettings' },
        { type: 'ref', id: 'global/globalactions' },
      ],
    },
    /*
    {
      type: 'category',
      label: 'API',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'aquaticcrates/api' },
      ],
    },
  ],
  */
  aquaticCrates: [
    {
      type: 'link',
      label: '💲 Purchase Here',
      href: 'https://aquatic.gg/products/aquaticcrates',
    },
    { type: 'doc', id: 'aquaticcrates/acrates-introduction' },
    {
      type: 'category',
      label: '📦 Basics',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'aquaticcrates/basic' },
      ],
    },
    {
      type: 'category',
      label: '🛠️ Miscellaneous',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'aquaticcrates/miscellaneous' },
      ],
    },
    {
      type: 'category',
      label: '🤖 API',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'aquaticcrates/api' },
      ],
    },
  ],
  eventsMania: [
    {
      type: 'link',
      label: '💲 Purchase Here',
      href: 'https://aquatic.gg/products/aquaticcrates',
    },
    { type: 'doc', id: 'eventsmania/eventsmania' },
    {
      type: 'category',
      label: '📦 Basics',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'eventsmania/basic' },
      ],
    },
    {
      type: 'category',
      label: '🤖 API',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'eventsmania/api' },
      ],
    },
  ],
  sentinel: [
    {
      type: 'link',
      label: '💲 Purchase Here',
      href: 'https://aquatic.gg/products/aquaticcrates',
    },
    { type: 'doc', id: 'sentinel/sentinel' },
    {
      type: 'category',
      label: '📦 Basics',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'sentinel/basic' },
      ],
    },
    {
      type: 'category',
      label: '🤖 API',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'sentinel/api' },
      ],
    },
  ],
  dialogues: [
    {
      type: 'link',
      label: '💲 Purchase Here',
      href: 'https://aquatic.gg/products/aquaticcrates',
    },
    { type: 'doc', id: 'dialogues/dialogues' },
    {
      type: 'category',
      label: '📦 Basics',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'dialogues/basic' },
      ],
    },
    {
      type: 'category',
      label: '🤖 API',
      collapsible: false,
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'dialogues/api' },
      ],
    },
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
